
-- 1.1
CREATE TABLE DetallePedido(
  idPedido int,
  idArticulo varchar(8),
  Cantidad int,
  Preventa money,
  SubTotal money)


ALTER TABLE DetallePedido ADD CONSTRAINT FK1 FOREIGN KEY (idArticulo) REFERENCES Articulo (idArticulo);
ALTER TABLE DetallePedido ADD CONSTRAINT FK2 FOREIGN KEY (idPedido) REFERENCES Pedido (idPedido);

--1.2
ALTER TABLE Pedido ADD CONSTRAINT Con1 DEFAULT 0 FOR Delivery;
ALTER TABLE Pedido ADD CONSTRAINT Con2 DEFAULT 0 FOR Estado;
ALTER TABLE Pedido ADD CONSTRAINT Con3 CHECK(Delivery IN (0,1));
ALTER TABLE Pedido ADD CONSTRAINT Con4 CHECK(Estado IN (0,1,2,3,4));

--1.3
ALTER TABLE Cliente ADD Visitas int NULL;
ALTER TABLE Cliente ADD CONSTRAINT Con6 CHECK(Visitas BETWEEN 0 AND 100);
UPDATE Cliente SET Visitas  = 0;

--2.1
SELECT T1.idEmpleado, T1.NomEmpleado, T2.NomCliente
FROM Empleado T1 INNER JOIN Pedido T2
on T1.idEmpleado = T2.idEmpleado;


--2.2
SELECT idCliente, NomCliente into CLOTS
From Cliente 

SELECT * FROM CLOTS

ALTER TABLE CLOTS ADD Cantidad int NULL;
UPDATE CLOTS SET CANTIDAD  = 0;

SELECT T1.idCliente, T1.NomCliente, COUNT(T2.idPedido) as Cantidad INTO RESUMEN
From Cliente T1 INNER JOIN Pedido T2
on T1.idCliente = T2.idCliente
GROUP BY t1.IdCliente, t1.NomCliente

UPDATE CLOTS SET CANTIDAD = T2.CANTIDAD 
FROM CLOTS T1 INNER JOIN RESUMEN T2 ON T1.IdCliente = T2.IdCliente

SELECT * FROM CLOTS
WHERE CANTIDAD = 0


--3.1

CREATE FUNCTION FUN11(@Nomcategoria varchar(20))
RETURNS TABLE
AS RETURN(
SELECT T1.NOMCLIENTE 
FROM CLIENTE T1 
INNER JOIN Pedido T2 ON T1.IdCliente = T2.IdCliente 
INNER JOIN DetallePedido T3 on t2.idPedido = t3.idPedido
INNER JOIN ARTICULO T4 ON T3.idArticulo = T3.idArticulo 
INNER JOIN Categoria T5 ON T4.IdCategoria = T5.IdCategoria
WHERE T5.NomCategoria = @Nomcategoria
)

--3.2 

CREATE PROCEDURE PROC1 @YEAR INT
AS BEGIN
SELECT T5.NOMCATEGORIA, COUNT(T2.IDPED 
FROM CLIENTE T1 
INNER JOIN Pedido T2 ON T1.IdCliente = T2.IdCliente 
INNER JOIN DetallePedido T3 on t2.idPedido = t3.idPedido
INNER JOIN ARTICULO T4 ON T3.idArticulo = T3.idArticulo 
INNER JOIN Categoria T5 ON T4.IdCategoria = T5.IdCategoria
GROUP BY T5.IDCATEGORIA

-- 3.3

CREATE TRIGGER TRI1 ON PEDIDO 
FOR INSERT 
AS BEGIN

CREATE FUNCTION FUNTO(@MONTO MONEY)
RETURNS FLOAT
BEGIN
RETURN CASE
	WHEN @MONTO BETWEEN 0.1 AND 30 THEN 0
	WHEN @MONTO BETWEEN 30.1 AND 50 THEN 0.02
	WHEN @MONTO BETWEEN 50.1 AND 100 THEN 0.04
	WHEN @MONTO BETWEEN 100.1 AND 500 THEN 0.06
	WHEN @MONTO BETWEEN 500.1 AND 1000 THEN 0.08
	WHEN @MONTO BETWEEN 1000.1 AND 10000 THEN 0.10
END
END
UPDATE INSTERTED SET MONTO = MONTO * DESC

SELECT * FROM PEDIDO
